### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by timvkleef** [code-orange/code-orange.nl#15]
- [x] replace odyssey video link: https://www.youtube.com/watch?v=lEj5m0IXZUI&list=PLDmHEiFMKAN9gbl1F0y1iI9QKjiwiu6LR&index=3
- [x] Change Github org profile link: https://github.com/code-orange
- [x] Make contact form smaller

**Comment by Arnoud-Bleeker** [comment]
Not yet live on code-orange.nl
