### ISSUE TITLE
Fix Vacancies page

### ISSUE THREAD

**Issue by timvkleef** [code-orange/code-orange.nl#17]

**Comment by Arnoud-Bleeker** [comment]
Pages have new style. there is no link to vacancies page on home page yet.

**Comment by timvkleef** [comment]
@Yorannn 

Could you check this please and put it live?

**Comment by timvkleef** [comment]
@Arnoud-Bleeker some feedback:

- [x] Change text below "interested" for all pages into "Fill in the contact form below or call us at +31(0)20 893 2941"
![image](https://user-images.githubusercontent.com/31925810/64855425-21731b00-d620-11e9-955d-c13cdb9c4e03.png)

//Can we use the same font style of the regular text above please? On every page.
<img width="608" alt="Knipsel" src="https://user-images.githubusercontent.com/31925810/65342743-a5ef0c00-dbd3-11e9-972f-0877748cdab9.PNG">

- [x] Add padding-top: 25px to h2 
![image](https://user-images.githubusercontent.com/31925810/64855494-48c9e800-d620-11e9-8296-8fa0dac51d8d.png)

- [x] Change title of Tim into "CTO and co-owner" // on all pages please (also the vacancy itself)

- [x] Check responsiveness and margins for header title on different screens. 
![image](https://user-images.githubusercontent.com/31925810/64856058-74999d80-d621-11e9-8c0f-e1f0bdc709c8.png)

**Comment by timvkleef** [comment]
http://code-orange.s3-website.eu-central-1.amazonaws.com/vacancies/

**Comment by timvkleef** [comment]
@Arnoud-Bleeker some feedback points. Could you tag me here when you are done?

**Comment by timvkleef** [comment]
@Arnoud-Bleeker Thanks, looks good. @Yorannn could you review the code and merge everything to stable please.

**Comment by Yorannn** [comment]
@Arnoud-Bleeker Wil je de link naar de vanacies page nog aanpassen. Graag neit direct naar index.html linken. Dat is niet nodig. https://code-orange.nl/vacancies/ is prima ook de target=blank weghalen

**Comment by timvkleef** [comment]
@Yorannn @Arnoud-Bleeker Wat is hier de status?

**Comment by Yorannn** [comment]
Done
